import {describe,expect,it,vi} from 'vitest';import type{SendEligibilityInput}from'@/lib/email/eligibility';
import fixture from './fixtures/apify-dataset.json';
import {normalizeApifyItem} from '@/lib/apify/adapter';import{ingestDataset}from'@/lib/apify/ingestion';import{qualifyCompany}from'@/lib/qualification/score';import{reviewTransition}from'@/lib/review/workflow';import{controlledSend,type OutboundStore}from'@/lib/email/controlled-send';import{processEmailEvent}from'@/lib/email/events';import{decideRetry}from'@/lib/jobs/retry';

describe('piloto mockado ponta a ponta',()=>{it('campanha → Apify → revisão → dry-run → entrega → resposta → CRM',async()=>{
 const campaign={id:'c1',status:'PAUSED',limit:20,costLimit:500};
 const items=fixture.map(normalizeApifyItem).filter(Boolean) as NonNullable<ReturnType<typeof normalizeApifyItem>>[];
 const imported=ingestDataset(items,new Set());expect(imported).toHaveLength(1);expect(imported[0].stage).toBe('REVIEW_PENDING');
 const evidence=[{id:'reachable',user_id:'u',company_id:'company',type:'WEBSITE_REACHABLE' as const,value:true,status:'CONFIRMED' as const,observed_at:'2026-09-15T10:00:00Z',expires_at:null,source_url:imported[0].business.sourceUrl!},{id:'cta',user_id:'u',company_id:'company',type:'HAS_CTA' as const,value:false,status:'CONFIRMED' as const,observed_at:'2026-09-15T10:00:00Z',expires_at:null,source_url:imported[0].business.website!}];
 const q=qualifyCompany({userId:'u',companyId:'company',decisionAt:'2026-09-15T12:00:00Z',evidence,gaps:[{gap_type:'NO_CONVERSION_PAGE',severity:5,confidence:1,status:'CONFIRMED'},{gap_type:'NO_LEAD_CAPTURE',severity:5,confidence:1,status:'CONFIRMED'}],contacts:[{email_verification_status:'VALID',is_decision_maker:true,hasPhone:true}],capacity:{reviewCount:120,rating:5,hasOpeningHours:true,hasAddress:true,hasPhone:true,hasMultipleServices:true,hasMultipleContacts:true,websiteReachable:true},timing:['ACTIVE_CAMPAIGN','NEW_SERVICE'],dataConfidence:{coverage:1,freshness:1,consistency:1,sourceCount:2},availableObservations:['WEBSITE_REACHABLE','HAS_CTA','HAS_FORM']});expect(q.recommended_action).toBe('READY_FOR_EMAIL');
 const stage=reviewTransition('REVIEW_PENDING','APPROVE',true);expect(stage).toBe('APPROVED_FOR_EMAIL');campaign.status='ACTIVE';
 const provider={send:vi.fn(async()=>({accepted:true as const,providerMessageId:'resend-1'}))};const store={persist:vi.fn(async()=>({id:'m1',existing:false})),markAccepted:vi.fn()} as OutboundStore;const eligibility:SendEligibilityInput={campaignStatus:'ACTIVE',leadStage:stage,leadApproved:true,contactEmail:items[0].email??null,emailVerificationStatus:'VALID',isSuppressed:false,hasReplied:false,hasHardBounced:false,hasUnsubscribed:false,alreadySentForStep:false,hoursSinceLastSend:null,minIntervalHours:24,senderIsActive:true,senderSpf:'PASS',senderDkim:'PASS',senderDmarc:'PASS',senderSentToday:0,senderDailyLimit:20,campaignSentToday:0,campaignDailyLimit:20,templateStatus:'APPROVED',messageHasIdentityAndOptOut:true,withinSendingWindow:true};const payload={from:'vendas@example.com',to:items[0].email!,subject:'Diagnóstico',text:'Identidade e opt-out',idempotencyKey:'lead:step:contact'};
 expect(await controlledSend({payload,eligibility,provider,store,env:{NODE_ENV:'production',EMAIL_DRY_RUN:'true'} as NodeJS.ProcessEnv})).toMatchObject({kind:'DRY_RUN'});expect(provider.send).not.toHaveBeenCalled();
 vi.mocked(store.persist).mockResolvedValue({id:'m1',existing:false});const sent=await controlledSend({payload,eligibility,provider,store,env:{NODE_ENV:'production',EMAIL_SENDING_ENABLED:'true',EMAIL_DRY_RUN:'false',POSTGRES_VALIDATED:'true',EMAIL_DNS_VALIDATED:'true'} as NodeJS.ProcessEnv});expect(sent.kind).toBe('SENT');
 const delivered=processEmailEvent('SENT','DELIVERED','delivered-1',new Set());expect(delivered.status).toBe('DELIVERED');const reply=processEmailEvent('DELIVERED','REPLIED','reply-1',new Set());expect(reply.effects.cancelRemainingSteps).toBe(true);expect(reply.effects.createTask).toBe(true);expect(reply.status).toBe('REPLIED');
 expect(decideRetry(3,3,'TRANSIENT').status).toBe('DEAD_LETTER');
 });});
